version: '3.9'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"

  app:
    build:
      context: .
    container_name: chat-senses
    depends_on:
      - qdrant
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: ["dockerize", "-wait", "tcp://qdrant:6333", "-timeout", "60s", "python", "app/main.py"]